version: "3.9"
services:
  
  cb-server:
    container_name: cb-server
    image: duncanfish/cheap-blue:cb-server
    ports:
      - "4000:4000"
  
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cbdb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: asdf
    ports:
      - "5050:80"
  
volumes:
  postgres-data:
  