version: "3.3"
services:
  
  cb-server:
    container_name: cb-server
    image: duncanfish/deployment-images:cb-server
    ports:
      - "80:4000"
  
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: duncan
      POSTGRES_PASSWORD_FILE: /secrets/postgres-password
      POSTGRES_DB: cbdb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./secrets/postgres-password:/secrets/postgres-password
  
volumes:
  postgres-data:
  